"""add_llm_config_table

Revision ID: 09fdc49e9a7d
Revises: cfd46a1b6f58
Create Date: 2026-01-17 21:53:00.334734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fdc49e9a7d'
down_revision: Union[str, None] = 'cfd46a1b6f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. llm_configs 테이블 생성
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # 2. conversations 테이블에 컬럼 추가 (SQLite batch mode 사용)
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_config_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(
            'fk_conversations_llm_config_id',
            'llm_configs',
            ['llm_config_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_llm_config_id', type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('llm_config_id')
    
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
