"""add llm_model_id FK to llm_configs

Revision ID: c61a688f053c
Revises: 565dbcc5f7e6
Create Date: 2026-01-25 18:33:27.406806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61a688f053c'
down_revision: Union[str, None] = '565dbcc5f7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('max_tokens_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # SQLite batch mode for FK support
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_model_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_llm_configs_llm_model_id', 'llm_models', ['llm_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_llm_configs_llm_model_id', type_='foreignkey')
        batch_op.drop_column('llm_model_id')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
